config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  #get 'home/index'

  
end

app/models/page.rb
class Page < ActiveRecord::Base
	validates :name, presence: true
	validates :category, presence: true
	validates :section, presence: true
	validates :title, presence: true
	validates :description, presence: true

	def category_enum
		['software','graphics','networking']
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@pages = Page.all
  	@footer = Page.where(section:"footer")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%for i in @pages do%>
	<%= i.name %> 
	
	<%= time_ago_in_words(i.created_at)%> ago
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBusiness</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
	<nav class="navbar navbar-inverse" role="navigation">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">My Business |</a>
		</div>
		<div>
			<ul class="nav navbar-nav navbar-left">
				<li><a href="#">Home</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><%=link_to "Admin", rails_admin_path%></li>
			</ul>
		</div>
	</nav>
<%= yield %>
<footer>
	<%for i in @footer do%>
	<%= i.name %> 
	<%= time_ago_in_words(i.created_at)%> ago
<% end %>
</footer>
</body>
</html>